
services:
  mongo:
    image: mongo:7.0.12
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - express-permit

  api:
    env_file:
      - .env
    build:
      context: ./api
      dockerfile: ../docker/api/Dockerfile #Affected by context? yes
      target: production
      args:
        - NODE_ENV=${NODE_ENV:-'production'}
    restart: always
    working_dir: /app
    environment:
      - NODE_ENV=${NODE_ENV:-'production'}
    ports:
      - 5050:5050
    networks:
      - express-permit
    depends_on:
      - mongo

  frontend:
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
      target: production
      args:
        - NODE_ENV=${NODE_ENV:-'production'}
    restart: always
    working_dir: /app
    environment:
      - NODE_ENV=${NODE_ENV:-'production'}
    ports:
      - 80:80
    networks:
      - express-permit
    depends_on:
      - api

volumes:
  mongo_data:
  node_modules:
networks:
  express-permit:
    driver: bridge