
services:
  mongo:
    image: mongo:7.0.12
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - express-permit

  api:
    build:
      context: ./api
      dockerfile: ../docker/api/Dockerfile.prod #Affected by context? yes
    container_name: api-app
    restart: unless-stopped
    working_dir: /app
    ports:
      - 5050:5050
    networks:
      - express-permit
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile.prod
    container_name: frontend-app
    restart: unless-stopped
    working_dir: /app
    ports:
      - 80:80
    networks:
      - express-permit
    depends_on:
      - api

volumes:
  mongo_data:
networks:
  express-permit:
    driver: bridge