
services:
  mongo:
    image: mongo:7.0.12
    restart: unless-stopped
    #ports:
    #  - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - express-permit

  api:
    build:
      context: ./api
      dockerfile: ../docker/api/Dockerfile #Affected by context? yes
    restart: unless-stopped
    volumes: #volumes: Always Uses Host Paths, Affected by context? no
      - ./api:/app
      - /app/node_modules # for persistent node_modules, this ignores local node_modules and usess the one from the container
    working_dir: /app
    ports:
      - 5050:5050
    networks:
      - express-permit
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile #Affected by context? yes
    restart: unless-stopped
    volumes:
      - ./frontend:/app #volumes: Always Uses Host Paths, Affected by context? no
      - /app/node_modules # for persistent node_modules, this ignores local node_modules and usess the one from the container
    working_dir: /app
    ports:
      - 5172:5172
    command: npm run dev -- --host
    networks:
      - express-permit
    depends_on:
      - api

volumes:
  mongo_data:
networks:
  express-permit:
    driver: bridge